# Generated by Django 6.0.2 on 2026-02-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('borrower_type', models.CharField(choices=[('PERSON', 'Person'), ('CORP', 'Corporation'), ('COOP', 'Cooperative')], default='PERSON', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('birth_or_incorp_date', models.DateField(blank=True, null=True)),
                ('primary_address', models.CharField(max_length=300)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('risk_rating', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('Call', 'Call'), ('Visit', 'Visit'), ('Demand Letter', 'Demand Letter'), ('Negotiation', 'Negotiation')], max_length=20)),
                ('remarks', models.TextField()),
                ('promise_to_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('promise_to_pay_date', models.DateField(blank=True, null=True)),
                ('staff_assigned', models.CharField(max_length=100)),
                ('next_action_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelinquencyStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delinquency_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('snapshot_type', models.CharField(choices=[('EVENT', 'Event-driven'), ('MONTH_END', 'Month-end')], default='EVENT', max_length=10)),
                ('days_past_due', models.IntegerField(default=0)),
                ('aging_bucket', models.CharField(blank=True, choices=[('30', '30 days'), ('60', '60 days'), ('90', '90 days'), ('180', '180 days'), ('360+', '360+ days')], max_length=10, null=True)),
                ('classification', models.CharField(choices=[('C', 'Current'), ('SM', 'Especially Mentioned'), ('SS', 'Substandard'), ('D', 'Doubtful'), ('L', 'Loss')], default='C', max_length=20)),
                ('npl_flag', models.BooleanField(default=False)),
                ('npl_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECLProvisionHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provision_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('provision_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('provision_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('classification', models.CharField(blank=True, max_length=20, null=True)),
                ('days_past_due', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('RULE_BASED', 'Rule-based'), ('IFRS9', 'IFRS 9'), ('IMPORT', 'Imported')], default='RULE_BASED', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exposure_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('snapshot_type', models.CharField(choices=[('EVENT', 'Event-driven'), ('MONTH_END', 'Month-end')], default='EVENT', max_length=10)),
                ('principal_outstanding', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accrued_interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accrued_penalty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('legal_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_exposure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('provision_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('provision_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_computed_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pn_number', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_type', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=10)),
                ('account_officer_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PERFORMING', 'Performing'), ('PAST_DUE', 'Past Due'), ('NPL', 'NPL'), ('WRITEOFF', 'Write-Off'), ('CLOSED', 'Closed')], default='PERFORMING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemedialStrategy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_type', models.CharField(choices=[('Intensive Collection', 'Intensive Collection'), ('Restructuring', 'Restructuring'), ('Compromise', 'Compromise'), ('Foreclosure', 'Foreclosure'), ('Legal Action', 'Legal Action'), ('Write-Off', 'Write-Off')], max_length=50)),
                ('strategy_start_date', models.DateField()),
                ('strategy_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('strategy_outcome', models.TextField(blank=True)),
            ],
        ),
    ]
