# Generated by Django 6.0.2 on 2026-02-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('borrower_id', models.CharField(max_length=20)),
                ('borrower_name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(max_length=50)),
                ('booking_date', models.DateField()),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maturity_date', models.DateField()),
                ('branch_code', models.CharField(max_length=10)),
                ('account_officer', models.CharField(max_length=100)),
                ('security_type', models.CharField(choices=[('Unsecured', 'Unsecured'), ('REM', 'REM'), ('CM', 'CM'), ('Mixed', 'Mixed')], max_length=20)),
                ('current_status', models.CharField(choices=[('Performing', 'Performing'), ('Past Due', 'Past Due'), ('NPL', 'NPL'), ('Written-Off', 'Written-Off')], max_length=20)),
                ('days_past_due', models.IntegerField()),
                ('npl_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
