# Generated by Django 6.0.2 on 2026-02-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('borrower_type', models.CharField(choices=[('PERSON', 'Person'), ('CORP', 'Corporation'), ('COOP', 'Cooperative')], default='PERSON', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('birth_or_incorp_date', models.DateField(blank=True, null=True)),
                ('primary_address', models.CharField(max_length=300)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('risk_rating', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pn_number', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_type', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=10)),
                ('account_officer_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PERFORMING', 'Performing'), ('PAST_DUE', 'Past Due'), ('NPL', 'NPL'), ('WRITEOFF', 'Write-Off'), ('CLOSED', 'Closed')], default='PERFORMING', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_master.borrower')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exposure_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('principal_outstanding', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accrued_interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accrued_penalty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('legal_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_exposure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('provision_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('provision_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_computed_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='account_master.loanaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelinquencyStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delinquency_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('days_past_due', models.IntegerField(default=0)),
                ('aging_bucket', models.CharField(blank=True, choices=[('30', '30 days'), ('60', '60 days'), ('90', '90 days'), ('180', '180 days'), ('360+', '360+ days')], max_length=10, null=True)),
                ('classification', models.CharField(blank=True, choices=[('SM', 'Especially Mentioned'), ('SS', 'Substandard'), ('D', 'Doubtful'), ('L', 'Loss')], max_length=20, null=True)),
                ('npl_flag', models.BooleanField(default=False)),
                ('npl_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delinquency_statuses', to='account_master.loanaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('Call', 'Call'), ('Visit', 'Visit'), ('Demand Letter', 'Demand Letter'), ('Negotiation', 'Negotiation')], max_length=20)),
                ('remarks', models.TextField()),
                ('promise_to_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('promise_to_pay_date', models.DateField(blank=True, null=True)),
                ('staff_assigned', models.CharField(max_length=100)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to='account_master.loanaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemedialStrategy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_type', models.CharField(choices=[('Intensive Collection', 'Intensive Collection'), ('Restructuring', 'Restructuring'), ('Compromise', 'Compromise'), ('Foreclosure', 'Foreclosure'), ('Legal Action', 'Legal Action'), ('Write-Off', 'Write-Off')], max_length=50)),
                ('strategy_start_date', models.DateField()),
                ('strategy_status', models.CharField(max_length=50)),
                ('strategy_outcome', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedial_strategies', to='account_master.loanaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
