# Generated by Django 6.0.2 on 2026-02-17 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrower',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionactivitylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionactivitylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delinquencystatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delinquencystatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eclprovisionhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eclprovisionhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exposure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exposure',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eclprovisionhistory',
            name='exposure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_history', to='account_master.exposure'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_master.borrower'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exposure',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='account_master.loanaccount'),
        ),
        migrations.AddField(
            model_name='delinquencystatus',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delinquency_statuses', to='account_master.loanaccount'),
        ),
        migrations.AddField(
            model_name='collectionactivitylog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to='account_master.loanaccount'),
        ),
        migrations.AddField(
            model_name='remedialstrategy',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedial_strategies', to='account_master.loanaccount'),
        ),
        migrations.AddField(
            model_name='remedialstrategy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remedialstrategy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eclprovisionhistory',
            index=models.Index(fields=['as_of_date'], name='account_mas_as_of_d_3070ef_idx'),
        ),
        migrations.AddIndex(
            model_name='eclprovisionhistory',
            index=models.Index(fields=['exposure', 'is_current'], name='account_mas_exposur_e36e07_idx'),
        ),
        migrations.AddIndex(
            model_name='eclprovisionhistory',
            index=models.Index(fields=['is_current', 'as_of_date'], name='account_mas_is_curr_e7a4a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='eclprovisionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('exposure',), name='uniq_current_provision_per_exposure'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['as_of_date'], name='account_mas_as_of_d_ebe48e_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['account', 'as_of_date'], name='account_mas_account_dc13d2_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['snapshot_type', 'as_of_date'], name='account_mas_snapsho_f8d705_idx'),
        ),
        migrations.AddConstraint(
            model_name='exposure',
            constraint=models.UniqueConstraint(fields=('account', 'as_of_date'), name='uniq_exposure_account_asof'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['as_of_date'], name='account_mas_as_of_d_4f71b5_idx'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['account', 'as_of_date'], name='account_mas_account_6a215a_idx'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['classification', 'as_of_date'], name='account_mas_classif_cdb67e_idx'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['npl_flag', 'as_of_date'], name='account_mas_npl_fla_0bd7c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='delinquencystatus',
            constraint=models.UniqueConstraint(fields=('account', 'as_of_date'), name='uniq_delinquency_account_asof'),
        ),
        migrations.AddConstraint(
            model_name='remedialstrategy',
            constraint=models.UniqueConstraint(condition=models.Q(('strategy_status', 'ACTIVE')), fields=('account', 'strategy_type'), name='unique_active_strategy_per_account'),
        ),
    ]
