# Generated by Django 6.0.2 on 2026-02-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedialstrategy',
            name='strategy_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
    ]
