# Generated by Django 6.0.2 on 2026-02-17 00:46

from django.db import migrations
from datetime import date

def populate_borrowers_and_accounts(apps, schema_editor):
    Borrower = apps.get_model('account_master', 'Borrower')
    LoanAccount = apps.get_model('account_master', 'LoanAccount')

    borrowers_data = [
        {'borrower_id': 'B001', 'full_name': 'Juan Dela Cruz', 'borrower_type': 'PERSON', 'primary_address': 'Cebu City'},
        {'borrower_id': 'B002', 'full_name': 'Maria Clara', 'borrower_type': 'PERSON', 'primary_address': 'Mandaue City'},
        {'borrower_id': 'B003', 'full_name': 'ABC Corporation', 'borrower_type': 'CORP', 'primary_address': 'Lapu-Lapu City'},
    ]

    for data in borrowers_data:
        Borrower.objects.get_or_create(borrower_id=data['borrower_id'], defaults=data)

    accounts_data = [
        {
            'loan_id': 'ACC001',
            'borrower_id': 'B001',
            'pn_number': 'PN001',
            'booking_date': date(2022, 1, 15),
            'maturity_date': date(2027, 1, 15),
            'original_principal': 500000.00,
            'interest_rate': 0.08,
            'loan_type': 'SME Loan',
            'branch_code': 'BR01',
            'status': 'PERFORMING'
        },
        {
            'loan_id': 'ACC002',
            'borrower_id': 'B002',
            'pn_number': 'PN002',
            'booking_date': date(2021, 6, 20),
            'maturity_date': date(2026, 6, 20),
            'original_principal': 250000.00,
            'interest_rate': 0.12,
            'loan_type': 'Personal Loan',
            'branch_code': 'BR01',
            'status': 'PAST_DUE'
        },
        {
            'loan_id': 'ACC003',
            'borrower_id': 'B003',
            'pn_number': 'PN003',
            'booking_date': date(2020, 11, 1),
            'maturity_date': date(2025, 11, 1),
            'original_principal': 2000000.00,
            'interest_rate': 0.07,
            'loan_type': 'Commercial Loan',
            'branch_code': 'BR02',
            'status': 'NPL'
        },
    ]

    for data in accounts_data:
        borrower = Borrower.objects.get(borrower_id=data['borrower_id'])
        data['borrower'] = borrower
        del data['borrower_id']
        LoanAccount.objects.get_or_create(loan_id=data['loan_id'], defaults=data)

class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0002_alter_remedialstrategy_strategy_status'),
    ]

    operations = [
        migrations.RunPython(populate_borrowers_and_accounts),
    ]
