# Generated by Django 6.0.2 on 2026-02-17 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0003_populate_borrowers_and_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['as_of_date'], name='account_mas_as_of_d_4f71b5_idx'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['account', 'as_of_date'], name='account_mas_account_6a215a_idx'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['npl_flag', 'as_of_date'], name='account_mas_npl_fla_0bd7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='delinquencystatus',
            index=models.Index(fields=['classification', 'as_of_date'], name='account_mas_classif_cdb67e_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['as_of_date'], name='account_mas_as_of_d_ebe48e_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['account', 'as_of_date'], name='account_mas_account_dc13d2_idx'),
        ),
    ]
