# Generated by Django 6.0.2 on 2026-02-17 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0004_delinquencystatus_account_mas_as_of_d_4f71b5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delinquencystatus',
            constraint=models.UniqueConstraint(fields=('account', 'as_of_date'), name='uniq_delinquency_account_asof'),
        ),
        migrations.AddConstraint(
            model_name='exposure',
            constraint=models.UniqueConstraint(fields=('account', 'as_of_date'), name='uniq_exposure_account_asof'),
        ),
    ]
