# Generated by Django 6.0.2 on 2026-02-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0005_delinquencystatus_uniq_delinquency_account_asof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delinquencystatus',
            name='snapshot_type',
            field=models.CharField(choices=[('EVENT', 'Event-driven'), ('MONTH_END', 'Month-end')], default='EVENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='delinquencystatus',
            name='classification',
            field=models.CharField(choices=[('C', 'Current'), ('SM', 'Especially Mentioned'), ('SS', 'Substandard'), ('D', 'Doubtful'), ('L', 'Loss')], default='C', max_length=20),
        ),
    ]
