# Generated by Django 6.0.2 on 2026-02-17 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0006_delinquencystatus_snapshot_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposure',
            old_name='provision_level',
            new_name='provision_rate',
        ),
        migrations.AddField(
            model_name='exposure',
            name='snapshot_type',
            field=models.CharField(choices=[('EVENT', 'Event-driven'), ('MONTH_END', 'Month-end')], default='EVENT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['snapshot_type', 'as_of_date'], name='account_mas_snapsho_f8d705_idx'),
        ),
    ]
