# Generated by Django 6.0.2 on 2026-02-17 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_master', '0007_rename_provision_level_exposure_provision_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECLProvisionHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provision_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('provision_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('provision_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('classification', models.CharField(blank=True, max_length=20, null=True)),
                ('days_past_due', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('RULE_BASED', 'Rule-based'), ('IFRS9', 'IFRS 9'), ('IMPORT', 'Imported')], default='RULE_BASED', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_history', to='account_master.exposure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['as_of_date'], name='account_mas_as_of_d_3070ef_idx'), models.Index(fields=['exposure', 'is_current'], name='account_mas_exposur_e36e07_idx'), models.Index(fields=['is_current', 'as_of_date'], name='account_mas_is_curr_e7a4a0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('exposure',), name='uniq_current_provision_per_exposure')],
            },
        ),
    ]
