# Generated by Django 6.0.2 on 2026-02-17 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromiseInstallment',
            fields=[
                ('installment_id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompromiseAgreement',
            fields=[
                ('compromise_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_total_exposure', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_compromise_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('approval_level', models.CharField(choices=[('AO', 'Account Officer'), ('MANAGER', 'Manager'), ('BOARD', 'Board')], max_length=10)),
                ('approval_date', models.DateField()),
                ('installment_flag', models.BooleanField(default=False)),
                ('rescission_clause_flag', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('RESCINDED', 'Rescinded'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=10)),
                ('number_of_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], max_length=10, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromise_agreements', to='account_master.loanaccount')),
            ],
        ),
    ]
