# Generated by Django 6.0.2 on 2026-02-17 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_master', '0002_initial'),
        ('compromise_agreement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiseagreement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromise_agreements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromiseagreement',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromise_agreements', to='account_master.remedialstrategy'),
        ),
        migrations.AddField(
            model_name='compromiseagreement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromise_agreements_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromiseinstallment',
            name='compromise_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='compromise_agreement.compromiseagreement'),
        ),
    ]
